name: CI

on:
  push:
    branches: [ runtest ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
			# - uses: actions/checkout@v2

			# - name: Build app
			#   run: |
			#     yarn install
			#     yarn build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.0.3
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          
      - name: Test SSH cmd
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo foo"