name: CI

on:
  push:
    branches: [ foo ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
			- uses: actions/checkout@v2

			- name: Build app
			  run: |
			    yarn install
			    yarn build